version: '3.9'
services:
  # api-service:
  #   image: api-service
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     API_PREFIX: "api/v1"
  #     PORT: "3000"
  #   networks:
  #     - dev_network

  db:
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest_base_dev
      - MYSQL_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dev_network

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: abc123
    ports:
      - '5432:5432'
    networks:
      - dev_network

  adminer:
    image: adminer:4-standalone
    ports:
      - "8081:8081"
    networks:
      - dev_network
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - dev_network

  graphql-engine:
    image: hasura/graphql-engine:v2.12.1
    ports:
      - '8888:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgresql://postgres:abc123@postgres:5432/postgres
      HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:abc123@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgresql://postgres:abc123@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      - dev_network

volumes:
  db_data:
  redis_data:
  pg_data:

networks:
  dev_network:
    driver: bridge
